# Generated by Django 4.2.5 on 2023-11-03 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='post_img')),
                ('name', models.CharField(max_length=50)),
                ('create_date', models.TimeField(auto_now_add=True)),
                ('short_desc', models.TextField(max_length=500)),
                ('full_desc', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
