# Generated by Django 4.2.5 on 2023-11-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migass', '0004_rename_full_desc_posts_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
